# ===== DataBase (Docker inside) =====
spring.datasource.url=jdbc:mysql://mysql-campus:3306/campus_ticket?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===== File URL =====
file.base.url=${FILE_BASE_URL:http://localhost:8080}

# ===== WeChat =====
wechat.appid=${WECHAT_APPID}
wechat.secret=${WECHAT_SECRET}

# ===== File Upload (Docker Container Path) =====
user.avatar.upload-dir=/app/data/avatar
org.avatar.upload-dir=/app/data/org_avatar
org.album.upload-dir=/app/data/org_album
venue.album.upload-dir=/app/data/venue_album
performance.post.upload-dir=/app/data/performance_post
staff.photo.upload-dir=/app/data/staff_photo
ticket.photo.upload-dir=/app/data/ticket_photo

# ===== Temporary Directories =====
performance.post.temp-dir=/app/data/temp/performance_post
staff.photo.temp-dir=/app/data/temp/staff_photo

# ===== logger =====
logging.file.name=/app/logs/application.log
logging.level.root=INFO
logging.level.org.example.campus_performance_ticketing=DEBUG

# ===== Actuator =====
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized