# Application Name
spring.application.name=campus_performance_ticketing

# SQL Init
spring.sql.init.mode=never

# JPA Public Config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT Public Config
jwt.secret=campus-performance-ticketing-secret-key-very-safe
jwt.expiration=604800000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
