spring.application.name=campus_performance_ticketing
# If env is production change dev to prod.
spring.profiles.active=dev

spring.sql.init.mode=never

jwt.secret=campus-performance-ticketing-secret-key-very-safe
# 7 days
jwt.expiration=604800000

# Dev env
user.avatar.base-url=http://localhost:8080
user.avatar.upload-dir=./data/avatar

# prod env
#user.avatar.base-url=https://yourdomain.com
#user.avatar.upload-dir=/opt/app/data/avatar


