### @env local


### 1.1 [演出举办者] Token (假设 openid_002 是演出 ID=1 的创建者)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "openid": "openid_002"
}

> {% client.global.set("organizer_token", response.body.token); %}


### 1.2 [普通用户/无关人员] Token (用于测试无权限)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "openid": "openid_003"
}

> {% client.global.set("user_token", response.body.token); %}


### 1.3 [管理员] Token (用于测试强制下架)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "openid": "openid_001"
}

> {% client.global.set("admin_token", response.body.token); %}


### 2.1 [举办者] 上传一个 Bilibili 录像
POST {{baseURL}}/media/add
Content-Type: application/json
Authorization: Bearer {{organizer_token}}

{
  "performanceId": 1,
  "type": 2,
  "platform": 2,
  "externalKey": "https://www.bilibili.com/video/BV1xx411c7mD",
  "title": "2023迎新晚会-全场回放",
  "sortOrder": 10
}

### 2.2 [举办者] 上传一个直播间链接
POST {{baseURL}}/media/add
Content-Type: application/json
Authorization: Bearer {{organizer_token}}

{
  "performanceId": 1,
  "type": 2,
  "platform": 1,
  "externalKey": "https://live.bilibili.com/123456",
  "title": "现场直播通道",
  "sortOrder": 1
}

### 2.3 [无关人员] 尝试上传 (预期失败 403/500)
POST {{baseURL}}/media/add
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
  "performanceId": 1,
  "type": 1,
  "platform": 3,
  "externalKey": "http://bad-link.com",
  "title": "非法上传"
}


### 3.1 任何人都可以查询列表
GET {{baseURL}}/media/list?performanceId=1
Accept: application/json
Authorization: Bearer {{user_token}}


### 4.1 [无关人员] 尝试删除 (预期失败)
DELETE {{baseURL}}/media/1
Accept: application/json
Authorization: Bearer {{user_token}}

### 4.2 [举办者] 删除自己上传的链接 (ID需要替换为实际存在的)
DELETE {{baseURL}}/media/1
Accept: application/json
Authorization: Bearer {{organizer_token}}

### 4.3 [管理员] 强制下架违规链接 (ID需要替换为实际存在的)
DELETE {{baseURL}}/media/2
Accept: application/json
Authorization: Bearer {{admin_token}}